AttributeError: module 'spikeextractors' has no attribute 'sorting_exporter_dict'
'sorting_exporter_dict' should be changed to 'sorting_extractor_dict'